---
- name: Playbook de Configuração
  hosts: all
  vars:
    ansible_ssh_private_key_file: /home/azureuser/trabalhoiac/private_key.pem
    idioma: "português"  # Definindo uma variável 'idioma' com valor padrão
  tasks:
    - name: Atualizar e atualizar pacotes apt
      become: true
      apt:
        update_cache: yes
        upgrade: safe

    - name: Instalar o pacote nginx no grupo web
      become: true
      package:
        name: nginx
        state: present
      when: "'web' in group_names"

    - name: Habilitar e iniciar o serviço nginx no grupo web
      become: true
      service:
        name: nginx
        state: started
      when: "'web' in group_names"
