name: Terraform CI

on:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Outros passos para linting e verificação de segurança...

  security:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Passos para segurança...

  terraform:
    needs: [lint, security]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # Passos para inicialização, planejamento e aplicação do Terraform...

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Gerar arquivo de inventário myhosts
        run: |
          echo "hosts:" > myhosts
          echo "%{ for vm in vms ~}" >> myhosts
          echo "${vm.name}:" >> myhosts
          echo "    ansible_host: ${vm.public_ip_address}" >> myhosts
          echo "%{ endfor ~}" >> myhosts
          echo "vars:" >> myhosts
          echo "    ansible_user: ${username}" >> myhosts

      - name: Executar playbook do Ansible
        run: |
          ansible-playbook -i myhosts playbook.yml
        env:
          VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}
