name: Terraform CI

on:
  push:
    branches: main

jobs:
  terraform-and-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Rodar Init do Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Criar um plano do Terraform
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}

      - name: Aplicar o plano do Terraform
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Verificar e Exibir Conteúdo do Inventário
        run: |
          if [ -f inventory.ini ]; then
            cat inventory.ini
          else
            echo "Arquivo de inventário não encontrado!"
            exit 1
          fi

      - name: Executar playbook do Ansible
        run: |
          ansible-playbook -i inventory.ini ansible/playbook.yml
        env:
          VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}
