name: Terraform CI

on:
  push:
    branches: main

jobs:
  terraform-and-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Rodar Init do Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Criar um plano do Terraform
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}

      - name: Aplicar o plano do Terraform
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Gerar arquivo de inventário myhosts
        run: |
          echo "hosts:" > myhosts
          echo "vars:" >> myhosts
          echo "    ansible_user: ${username}" >> myhosts
          echo "" >> myhosts  # Adicionar uma linha em branco entre 'vars' e 'hosts' se necessário
          for vm in $vms; do
            echo "  ${vm['name' ]}:" >> myhosts
            echo "    ansible_host: ${vm['public_ip_address']}" >> myhosts
          done

      - name: Exibir conteúdo do arquivo myhosts
        run: cat myhosts

      - name: Executar playbook do Ansible
        run: |
          ansible-playbook -i myhosts ansible/playbook.yml
        env:
          VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}
